import streamlit as st
import pandas as pd
import plotly.express as px

                                    
from llm_summarizer import generate_executive_summary, generate_targeted_campaign

                                       
st.set_page_config(page_title="Restaurant Intelligence Hub", layout="wide", page_icon="")
st.title(" Restaurant Intelligence & Marketing Hub")

@st.cache_data
def load_and_prep_data():
                   
    df = pd.read_csv("data/restaurant_users_confirm.csv")
    
                                         
    def get_sentiment(score):
        if score >= 4: return "Positive"
        elif score <= 2: return "Negative"
        return "Neutral"
    df['Sentiment'] = df['Feedback Score (1-5)'].apply(get_sentiment)
    
                                                         
                                                     
    df['Risk_Status'] = "Safe"
    df.loc[(df['Feedback Score (1-5)'] <= 2) | (df['Visit Frequency'] == 'Low'), 'Risk_Status'] = "High Risk"
    
    return df

df = load_and_prep_data()

                            
st.sidebar.header(" Filter Dataset")
selected_sentiment = st.sidebar.multiselect("Sentiment", options=df['Sentiment'].unique(), default=df['Sentiment'].unique())
selected_freq = st.sidebar.multiselect("Visit Frequency", options=df['Visit Frequency'].unique(), default=df['Visit Frequency'].unique())
selected_payment = st.sidebar.multiselect("Payment Method", options=df['Payment Method'].unique(), default=df['Payment Method'].unique())

               
filtered_df = df[
    (df['Sentiment'].isin(selected_sentiment)) & 
    (df['Visit Frequency'].isin(selected_freq)) & 
    (df['Payment Method'].isin(selected_payment))
]

                                                 
tab1, tab2, tab3 = st.tabs([" Financial & Menu Analytics", " Churn & Marketing Engine", " AI Executive Summary"])

                                            
                                   
                                            
with tab1:
    st.markdown("### Top-Line Metrics")
    col1, col2, col3, col4 = st.columns(4)
    
    total_revenue = filtered_df['AMOUNT SPENT ON THAT DAY(20/10/2024)'].sum()
    avg_ticket = filtered_df['AMOUNT SPENT ON THAT DAY(20/10/2024)'].mean()
    
    col1.metric("Total Customers", len(filtered_df))
    col2.metric("Total Revenue", f"₹{total_revenue:,.0f}")
    col3.metric("Average Ticket Size", f"₹{avg_ticket:,.2f}")
    col4.metric("Average Feedback", f"{filtered_df['Feedback Score (1-5)'].mean():.1f} / 5.0")
    
    st.markdown("---")
    
                     
    chart_col1, chart_col2 = st.columns(2)
    
    with chart_col1:
        st.markdown("**Revenue Generated by Dish**")
                                           
        dish_revenue = filtered_df.groupby('Favorite Dish')['AMOUNT SPENT ON THAT DAY(20/10/2024)'].sum().reset_index()
        fig_dish = px.bar(dish_revenue, x='Favorite Dish', y='AMOUNT SPENT ON THAT DAY(20/10/2024)', 
                          color='Favorite Dish', text_auto='.2s', title="Menu Engineering (Gross Revenue)")
        st.plotly_chart(fig_dish, use_container_width=True)
        
    with chart_col2:
        st.markdown("**Payment Method Preferences**")
        fig_pay = px.pie(filtered_df, names='Payment Method', values='AMOUNT SPENT ON THAT DAY(20/10/2024)', 
                         hole=0.4, title="Revenue Share by Payment Type")
        st.plotly_chart(fig_pay, use_container_width=True)

                                            
                                            
                                            
with tab2:
    st.markdown("### Predictive Churn Analysis")
    st.markdown("Identifying high-value customers who are at risk of not returning.")
    
                                                         
    risk_df = filtered_df[filtered_df['Risk_Status'] == 'High Risk']
    
    col_risk1, col_risk2 = st.columns([1, 2])
    
    with col_risk1:
                                                    
        risk_counts = filtered_df['Risk_Status'].value_counts().reset_index()
        fig_risk = px.pie(risk_counts, names='Risk_Status', values='count', 
                          color='Risk_Status', color_discrete_map={'Safe': '#2ecc71', 'High Risk': '#e74c3c'},
                          hole=0.5, title="Customer Base Health")
        st.plotly_chart(fig_risk, use_container_width=True)
        
        st.metric("Total Revenue at Risk", f"₹{risk_df['AMOUNT SPENT ON THAT DAY(20/10/2024)'].sum():,.0f}")
        
    with col_risk2:
        st.markdown("**Action Center: High-Value, At-Risk Customers**")
                                                  
        action_targets = risk_df.sort_values(by='AMOUNT SPENT ON THAT DAY(20/10/2024)', ascending=False).head(10)
        st.dataframe(action_targets[['USER ID', 'Favorite Dish', 'AMOUNT SPENT ON THAT DAY(20/10/2024)', 'Feedback Score (1-5)']], use_container_width=True)
        
        st.markdown("####  Generate Win-Back Campaign")
        st.write("Select an at-risk user ID from the table above to auto-generate a personalized SMS offer.")
        
        selected_user = st.selectbox("Select Target User ID:", options=action_targets['USER ID'].tolist())
        
        if st.button("Generate SMS"):
            with st.spinner("Gemini is drafting the campaign..."):
                user_data = action_targets[action_targets['USER ID'] == selected_user].iloc[0]                
                sms_copy = generate_targeted_campaign(
                    user_data['Favorite Dish'], 
                    user_data['Payment Method'], 
                    user_data['AMOUNT SPENT ON THAT DAY(20/10/2024)'],
                    user_data['Feedback Score (1-5)']
                )
                st.success(f"Targeting User {selected_user}")
                st.info(f"📱 **SMS:** {sms_copy}")

                                            
                                        
                                            
with tab3:
    st.markdown("###  Generative AI Insights")
    st.write("Click below to have Gemini analyze the currently filtered dataset and provide structural business advice.")
    
    if st.button("Generate Executive Summary"):
        with st.spinner("Gemini is analyzing the data trends..."):
            summary = generate_executive_summary(filtered_df)
            st.success("Analysis Complete")
            st.info(summary)
            
    st.markdown("---")
    st.markdown("### Raw Database Access")
    st.dataframe(filtered_df, use_container_width=True)